# Load base open VSCode Server image
FROM gitpod/openvscode-server

# switch to root to install packages...
USER root 

# Update applications in base image
RUN apt-get -y update && apt-get install -y

# Install Clang Compiler for C++20
RUN apt-get -y install clang
RUN apt-get -y install build-essential gdb

# Install Clang Compiler for Haskell
RUN apt-get -y install ghc

# Install Python 3.8
RUN apt-get -y install python3.8


# Change back to default user
USER openvscode-server
